INSERT INTO Objective (Description, NumberOfSteps, Type)
VALUES 
	("Choose your role between developer or IT operator by going thorugh one of the doors", 1, ""),
	("Head to the Project Manager Office to know the project you will be envolved on", 1, ""),
	("Have a look to the Kanban board", 1, ""),
	("Head to the Project Manager Office to solve the recent issue", 1, ""),
	("Communicate the last changes to the development team", 1, ""),
	("Communicate the last changes to the IT operations team", 1, ""),
	("Head to the development office and develop the required features", 1, "Java"),
	("Head to the development office and develop the required features", 2, "Java"),
	("Head to the development office and develop the required features", 1, "JS"),
	("Head to the development office and develop the required features", 3, "JS"),
	("Head to the development office and develop the required features", 1, "Database"),
	("Push your changes to the repository", 1, ""),
	("Watch the execution of the pipeline", 1, ""),
	("Head to the development office and document the changes introduced", 1, ""),
	("Head to the development office and document the changes introduced", 2, ""),
	("Head to the development office and solve the bug introduced previously", 1, ""),
	("Head to the operations team side to look at the metrics of the deployed software", 1, ""),
	("Share resposabilities and develop a script to solve a stability issue of the deployed software", 1, "OpsScript"),
	("Deliver the script to the operations team side", 1, ""),
	("Document the changes introduced to help operations team to understand the softwaree", 1, ""),
	("Head to the operations team side and have a meeting with operations team members", 1, ""),
	("Head to the development office and solve the bug reported by operations team", 1, "Java"),
	("Head to the operations team side and attend to the workshop to promote communication and collaboration", 1, ""),
	("Head to the operations office and write the script to scale the production environment", 1, "OpsScript"),
	("Head to the operations office and write the script to scale the production environment", 2, "OpsScript"),
	("Push your changes to the production environment (head to the elevator)", 1, ""),
	("Share responsabilities and help developers by developing the features they asked for", 1, "Java"),
	("Head to the operations office and monitor the state of the deployed software", 1, "Statistics"),
	("Head to the operations office and monitor the state of the deployed software", 3, "Statistics"),
	("Head to the Project Manager Office and share the statistics obtained", 1, ""),
	("Head to the development team side and discuss about the stability problem in production", 1, ""),
	("Head to the customer feedback section to attend the ticket they sent", 1, ""),
	("Head to the operations office and document the solution for the customer", 1, "Solution"),
	("Deliver the solution to the customer", 1, ""),
	("Head to the development team side to let them know the solution to the production problem", 1, ""),
	("Head to the development team side to report a production bug", 1, ""),
	("Head to the development team side and have a meeting with development team members", 1, ""),
	("Head to the development team side and attend to a course of soft skills", 1, "");
	