INSERT OR REPLACE INTO Solution (SolutionId, EffectId, ProblemId, Cost, Profit, Description)
VALUES
	(1, 1, 1, 100000, 0, "I suggest to carry out a workshop with both teams, having DevOps experts involved"),
	(2, 3, 1, 100000, 0, "I suggest to carry out a workshop with both teams, having DevOps experts involved"),
	(2, 7, 1, 100000, 0, "I suggest to carry out a workshop with both teams, having DevOps experts involved"),
	(3, 10, 2, 10000, 0, "I suggest to have meetings with them and show the results before and after adopting DevOps"),
	(4, 10, 2, 5000, 0, "I suggest to have a meeting with them and show them the advantages of DevOps"),
	(4, 12, 2, 5000, 0, "I suggest to have a meeting with them and show them the advantages of DevOps"),
	(5, 13, 3, 200000, 0, "I suggest to train them through online courses and certifications"),
	(5, 16, 3, 200000, 0, "I suggest to train them through online courses and certifications"),
	(6, 3, 3, 150000, 0, "I suggest to allocate 5 hours per week to let them train by their own based on the skills they need"),
	(7, 12, 3, 200000, 0, "I suggest to implement a training environment where employeees are able to experiment"),
	(7, 15, 3, 200000, 0, "I suggest to implement a training environment where employeees are able to experiment"),
	(7, 21, 3, 200000, 0, "I suggest to implement a training environment where employeees are able to experiment"),
	(8, 12, 4, 20000, 0, "I suggest to conduct short meetings to encourage communication between teams"),
	(8, 20, 4, 20000, 0, "I suggest to conduct short meetings to encourage communication between teams"),
	(9, 3, 4, 0, 0, "I suggest to communicate more frequently through internal documentation"),
	(10, 12, 7, 50000, 0, "I think that it is a great idea as it promotes the alignment of goals"),
	(10, 14, 7, 50000, 0, "I think that it is a great idea as it promotes the alignment of goals"),
	(11, 5, 7, 0, 0, "I think we should leave it to the next project and learn from our errors"),
	(11, 19, 7, 0, 0, "I think we should leave it to the next project and learn from our errors"),
	(12, 12, 8, 0, 0, "I suggest to put them in top priority for the current sprint of development team"),
	(12, 17, 8, 0, 0, "I suggest to put them in top priority for the current sprint of development team"),
	(12, 13, 8, 0, 0, "I suggest to put them in top priority for the current sprint of development team"),
	(13, 17, 8, 0, 50000, "I suggest to keep the change management process as it is"),
	(13, 18, 8, 0, 50000, "I suggest to keep the change management process as it is"),
	(14, 15, 8, 0, 0, "I suggest to let the development team decide the priorization of open bugs"),
	(14, 17, 8, 0, 0, "I suggest to let the development team decide the priorization of open bugs"),
	(15, 12, 13, 100000, 0, "I suggest to review that development, pre-production and production environments are well replicated"),
	(15, 14, 13, 100000, 0, "I suggest to review that development, pre-production and production environments are well replicated"),
	(16, 4, 13, 50000, 0, "I suggest to include more tests regarding non-functional features in the testing process"),
	(17, 20, 13, 50000, 0, "I suggest that development and operations handle more meetings with QA"),
	(17, 13, 13, 50000, 0, "I suggest that development and operations handle more meetings with QA"),
	(18, 6, 10, 200000, 0, "I suggest to migrate the architecture to one based on microservices"),
	(18, 4, 10, 200000, 0, "I suggest to migrate the architecture to one based on microservices"),
	(19, 21, 10, 0, 0, "I suggest to keep the current architecture"),
	(19, 19, 10, 0, 0, "I suggest to keep the current architecture"),
	(20, 12, 9, 50000, 0, "I suggest to open a formal communication channel between development and operations teams for feedback"),
	(20, 13, 9, 50000, 0, "I suggest to open a formal communication channel between development and operations teams for feedback"),
	(21, 15, 9, 0, 50000, "I suggest to keep the communication via e-mail between both teams"),
	(21, 17, 9, 0, 50000, "I suggest to keep the communication via e-mail between both teams"),
	(21, 18, 9, 0, 50000, "I suggest to keep the communication via e-mail between both teams");